version: '3.8'

services:
  news_crawler_api:
    image: news_crawler
    container_name: news_crawler_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8200:80
    command: ["python", "/app/crawler/manage.py", "runserver", "0:80"]
    depends_on:
      - news_crawler_chrome
    restart: unless-stopped
  
  news_crawler_worker:
    image: news_crawler
    container_name: news_crawler_worker
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app/crawler
    command: ["celery", "-A", "crawler", "worker", "-l", "info", "--pidfile=", "--concurrency=1"]
    depends_on:
      - news_crawler_redis
      - news_crawler_chrome
    restart: unless-stopped
  
  news_crawler_beat:
    image: news_crawler
    container_name: news_crawler_beat
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app/crawler
    command: ["celery", "-A", "crawler", "beat", "-l", "info", "--pidfile="]
    depends_on:
      - news_crawler_redis
      - news_crawler_chrome
    restart: unless-stopped
  
  news_crawler_chrome:
    image: selenium/standalone-chrome
    container_name: news_crawler_chrome
    restart: unless-stopped

  news_crawler_redis:
    image: redis
    container_name: news_crawler_redis
    restart: unless-stopped

networks:
  default:
    external:
      name: army
