version: '3.8'

services:
  news_crawler_api:
    image: news_crawler
    container_name: news_crawler_api
    command: ["python", "/app/manage.py", "runserver", "0:80"]
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8200:80"
    depends_on:
      - qbar_db
    restart: unless-stopped
  
  news_crawler_worker:
    image: news_crawler
    container_name: news_crawler_worker
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["celery", "-A", "app", "worker", "-l", "info", "--pidfile="]
    restart: unless-stopped
  
  news_crawler_beat:
    image: news_crawler
    container_name: news_crawler_beat
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["celery", "-A", "app", "beat", "-l", "info", "--pidfile="]
    restart: unless-stopped
  
  news_crawler_chrome:
    image: selenium/standalone-chrome
    container_name: news_crawler_chrome
    restart: unless-stopped

  news_crawler_redis:
    image: redis
    container_name: news_crawler_redis
    restart: unless-stopped
